# Generated by Django 5.1.3 on 2024-12-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='identifiant',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='duree',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='annee',
        ),
    ]
